version: '2'
services:
  php:
    container_name: graphql_demo_php
    build:
      context: ./docker/php/
    working_dir: /var/www
    depends_on:
      - db
    volumes:
      - ./:/var/www
    links:
      - db:db_node
    stdin_open: true
    tty: true

  # nginx
  nginx:
    container_name: graphql_demo_nginx
    image: youshido/nginx
    volumes_from:
      - php
    ports:
      - 8500:80
    links:
      - php

  # database
  db:
    container_name: graphql_demo_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony